/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import accesoDatos.AccesoDatosMySql;
import accesoDatos.Tarjeta_Cliente_PrepagoD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Tarjeta_Cliente_Prepago;


/**
 *
 * @author Esmar
 */
public class ofrmMantenimientoTarjetaPrepago extends javax.swing.JDialog {
    
    AccesoDatosMySql conexion;
    
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private String[] cabeceras = {"Código", "Cédula_Cliente", "Nombre_Cliente","Saldo Actual","Porcentaje Descuento"};
    private String[][] datos = new String[0][5];

    private void refrescar() {
        Tarjeta_Cliente_PrepagoD pTarjeta = new Tarjeta_Cliente_PrepagoD(this.conexion);
        ArrayList tarjetas = (ArrayList) pTarjeta.consultarTarjetaPrepago();
        if (pTarjeta.isError()) {
            JOptionPane.showMessageDialog(null,
                    "Error consultando a la base de datos, detalle técnico:" + pTarjeta.getErrorMsg());
        } else {
            this.datos = new String[tarjetas.size()][5];
            for (int i = 0; i < tarjetas.size(); i++) {
                Tarjeta_Cliente_Prepago aux = (Tarjeta_Cliente_Prepago) tarjetas.get(i);
                this.datos[i][0] = aux.getCodigo();
                this.datos[i][1] = aux.getCedula_cliente();
                this.datos[i][2] = aux.getNombre_cliente();
                this.datos[i][3] = String.valueOf(aux.getSaldo_actual());
                this.datos[i][4] = String.valueOf(aux.getPorcentaje_descuento());
                
            }
            this.modelo.setDataVector(datos, cabeceras);
            this.tblTarjetas.setModel(modelo);
        }
    }       
    /**
     * Creates new form ofrmMantenimientoTarjetaPrepago
     */
    public ofrmMantenimientoTarjetaPrepago(java.awt.Frame parent, boolean modal,AccesoDatosMySql pConexion) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.conexion=pConexion;
        refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarjetas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblTarjetas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        frmEdicionTarjetas ofrmTarjeta = new frmEdicionTarjetas(null,true);
        ofrmTarjeta.setVisible(true);
        if(ofrmTarjeta.isAceptar()){
          Tarjeta_Cliente_Prepago oTarjeta = new Tarjeta_Cliente_Prepago(ofrmTarjeta.getTxtCodigo(),ofrmTarjeta.getTxtCedula(),ofrmTarjeta.getTxtCliente(),ofrmTarjeta.getSpnSaldo(),ofrmTarjeta.getSpnPorcentaje());
          Tarjeta_Cliente_PrepagoD oTarjetaD = new Tarjeta_Cliente_PrepagoD(conexion);
          oTarjetaD.insertarTarjetaPrepago(oTarjeta);
          if(oTarjetaD.isError()) {
                JOptionPane.showMessageDialog(null,
                        "Error consultando a la base de datos, detalle técnico:" + oTarjetaD.getErrorMsg());
            } else {
                this.refrescar();
            }
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.datos.length > 0) {
            int fila = this.tblTarjetas.getSelectedRow();
            if (fila >= 0) {
                String pCedulaAnterior = this.datos[fila][0];
                frmEdicionTarjetas ofrm = new frmEdicionTarjetas(null, true,this.datos[fila][0], this.datos[fila][1], this.datos[fila][2],Double.parseDouble(this.datos[fila][3]), Double.parseDouble(this.datos[fila][4]));
                ofrm.setVisible(true);
                if (ofrm.isAceptar()) {
                    Tarjeta_Cliente_Prepago oTarjeta = new Tarjeta_Cliente_Prepago(ofrm.getTxtCodigo(),ofrm.getTxtCedula(),ofrm.getTxtCliente(),ofrm.getSpnSaldo(),ofrm.getSpnPorcentaje());
                    Tarjeta_Cliente_PrepagoD oTarjetaD = new Tarjeta_Cliente_PrepagoD(conexion);
                    oTarjetaD.actualizarTarjetaPrepago(oTarjeta, pCedulaAnterior);
                    if (oTarjetaD.isError()) {
                        JOptionPane.showMessageDialog(null,
                            "Error consultando a la base de datos, detalle técnico:" + oTarjetaD.getErrorMsg());
                    } else {
                        this.refrescar();
                    }
                }
            }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (this.datos.length > 0) {
            int respuesta = JOptionPane.showConfirmDialog(rootPane,"¿Esta seguro que desealo Eliminarlo? Si o No?", "Confirmación" , JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
            int fila = this.tblTarjetas.getSelectedRow();
            if (fila >= 0) {
                    Tarjeta_Cliente_Prepago pTarjeta = new Tarjeta_Cliente_Prepago(this.datos[fila][0], this.datos[fila][1], this.datos[fila][2], Double.parseDouble(this.datos[fila][3]), Double.parseDouble(this.datos[fila][4]));
                    Tarjeta_Cliente_PrepagoD oTarjetaD = new Tarjeta_Cliente_PrepagoD(conexion);
                    oTarjetaD.borrarTarjetaPrepago(pTarjeta);
                    if (oTarjetaD.isError()) {
                    JOptionPane.showMessageDialog(null,
                            "Error consultando a la base de datos, detalle técnico:" + oTarjetaD.getErrorMsg());
                    } else {
                        this.refrescar();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTarjetas;
    // End of variables declaration//GEN-END:variables
}
